version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-todo
    environment:
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopass
      POSTGRES_DB: todolist
    ports:
      - "5666:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: